### ISSUE TITLE
Unable to open ERROR Could not load notebook 'C:\Program Files (x86)\KeepNote\Network +

### ISSUE THREAD

**Issue by ransacrob** [mdrasmus/keepnote#745]
Please help - I am curently studying CEH and have been using Keepnote for all of my notes, to which now Keepnote seems to be not able to open my notes and I have essentially lost months of notetaking. Slightly stressful.... I can see 'Network +' folder when trying to open from keepnote but not from Explorer. Here is the error log below. 

I can see similar issues which say to amend the node.xml etc, I am unable to find this and edit it - i need a reasonably simple instruction (if possible) to fix this as I am not able to write code as yet and nor am i expeienced in this field. PLEASE help :)

Traceback (most recent call last):
  File "keepnote\gui\__init__.pyc", line 568, in func
  File "keepnote\notebook\__init__.pyc", line 1405, in load
  File "keepnote\notebook\connection\fs\__init__.pyc", line 888, in get_rootid
  File "keepnote\notebook\connection\fs\__init__.pyc", line 775, in _read_root
  File "keepnote\notebook\connection\fs\__init__.pyc", line 960, in _read_node
  File "keepnote\notebook\connection\fs\__init__.pyc", line 1060, in _read_attr
ConnectionError: Error reading meta data file 'C:\Program Files (x86)\KeepNote\Network +\node.xml'
![keepnote error](https://user-images.githubusercontent.com/60626575/73695024-2c167580-46d1-11ea-9761-3db9f7c8ecdf.png)
![keepnote error2](https://user-images.githubusercontent.com/60626575/73695094-51a37f00-46d1-11ea-8648-4bd5731ae94c.png)

Thank you!

**Comment by Aggelos11** [comment]
Same for me
