### ISSUE TITLE
Notebooks won't open after closing the program with them still open

### ISSUE THREAD

**Issue by Koby-kun** [mdrasmus/keepnote#746]
Since yesterday, when I turned on my laptop and tried to open some notes I kept on KeepNote, it would only give me an error and not open.
I also can't seem to open any new notebooks.
I use windows 10, 64 bit and KeepNote 0.7.8.
When trying to open a notebook, this is the error log left from it.

_Traceback (most recent call last):
  File "keepnote\gui\__init__.pyc", line 568, in func
  File "keepnote\notebook\__init__.pyc", line 1405, in load
  File "keepnote\notebook\connection\fs\__init__.pyc", line 888, in get_rootid
  File "keepnote\notebook\connection\fs\__init__.pyc", line 775, in _read_root
  File "keepnote\notebook\connection\fs\__init__.pyc", line 960, in _read_node
  File "keepnote\notebook\connection\fs\__init__.pyc", line 1060, in _read_attr
ConnectionError: Error reading meta data file 'C:\Program Files (x86)\KeepNote\Reef Quarry\node.xml'_

The error is the exact same for any other pre existing notebooks I try opening, except the name of the notebook is different obviously.

I think I may have closed the files incorrectly somehow, but I don't know how to fix it from here.
Since I can only access the folders for the notebooks themselves in KeepNote, where it doesn't let me delete anything, I don't know how to get rid of corrupted files in the notebooks if that's the issue, I can access anything else from the regular folders.

**Comment by the40Keeper** [comment]
I am facing the same issue. Have you been able to resolve this?
Same specs

**Comment by 40Keeper** [comment]
I SOLVED THIS USING CHAT GPT!!!

Check for VirtualStore (Windows Compatibility Files):

Sometimes, files stored by older applications get redirected to a virtual storage area in Windows called VirtualStore. This happens especially with programs that save files in protected directories like Program Files (x86).
Navigate to **C:\Users\<YourUsername>\AppData\Local\VirtualStore\Program Files (x86)\KeepNote**. (Replace <YourUsername> with your actual username.)
Look for the FOLDERNAME folder here. If you find it, you can copy it to a safer location like your Documents folder.
    
Once this is done, I faced an error in opening the Notebook, so I deleted all content of the main node.xml file, deleted all .tmp files and created a new node.xml file with only the content < node >< /node > in it, and changed the contents of notebook.nbk to < notebook >< /notebook >

Then it ran. After one hour of struggle. Sweat. Tears. But it ran !!!!!!!!!!!!
